### ISSUE TITLE
Select specific slide based on a button click

### ISSUE THREAD

**Issue by lakerphan4life** [michu2k/SimpleSlider#2]
Hi there, 

Not an issue, more of a question. How can I trigger the slider to show a specific slide (ex. slide #2), when clicking a button that corresponds to that slide (ex. button #2)?

I have an accordion, each accordion tab corresponds to an image in the slider, so curious to see if this capability exists with this project

**Comment by michu2k** [comment]
Hi @lakerphan4life 
Yes, it is possible. You can do something like this:

```html
<button class="btn" data-slide="0">Slide 1</button>
<button class="btn" data-slide="1">Slide 2</button>
<button class="btn" data-slide="2">Slide 3</button>
```

```javascript
const simpleslider = new SimpleSlider('.page-slider');
const btns = document.querySelectorAll('.btn');

[...btns].map(btn => {
  btn.addEventListener('click', () => {
    // Get slide index
    const slideIdx = btn.getAttribute('data-slide');
    const slideIndex = parseInt(slideIdx);

    // Update slider index (This function will return index value after correction)
    const index = simpleslider.updateIndex(slideIndex);
    simpleslider.index = index;

    // Change slide
    simpleslider.changeSlide();
  });
});
```

In the next update, I will try to add additional function for this case :)

**Comment by lakerphan4life** [comment]
Awesome!! Thanks so much :)
