### ISSUE TITLE
How to stop autoplay?

### ISSUE THREAD

**Issue by diegosomar** [michu2k/SimpleSlider#8]
I would like to pause autoplay when a specific slide are shown (video).

I have a [fiddle](https://jsfiddle.net/diegosomar/fqspeku7/) with an example:

In the browser console, when I call `slider.resetAutoplay()`, autoplay stops correctly.
But, when I implement in the code (above), doesn't stop. There's no error in console.

Someone can help me how to stop autoplay?

**Comment by michu2k** [comment]
Hi @diegosomar 
For now, you need to set `autoplay` to `false` but it will certainly be simplified in future updates.

```javascript
if ( activeSlide.getAttribute('data-type') == "video" ){
    console.log("Should stop now")
    slider.options.autoplay = false;
    slider.resetAutoplay();
} else {
    if (!slider.options.autoplay) {
        console.log('enable autoplay');
        slider.options.autoplay = true;
        slider.autoplay();
    }
}
```

**Comment by diegosomar** [comment]
Hello @michu2k, tks! It works!

Do you know how to do this if the first slide is a video?
When I put this code in method `onInit`, I have an error (slider not defined).
If first slide is a video, autoplay is false.

**Comment by michu2k** [comment]
You have right, slider should be defined in the onInit function.
In fact, you can use the onChange function, just set ʻautoplay: false` and the rest of the codes are the same as above.

**Comment by diegosomar** [comment]
Tks @michu2k!
